[package]
name = "calpino"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
pulldown-cmark = "=0.7.0"
ron = "0.8.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
tokio = "1.38.0"
csv = "1.3.0"
eframe = "0.27.2"
egui = "0.27.2"
epi = "0.17.0"
